import { IncomeCategory, PaymentMethod, Prisma } from '@prisma/client';
import { prisma } from '../config/prisma';
import { andWhere, findScoped, paginate, searchFilter } from '../repositories/base.repository';
import { resolveSort } from '../utils/pagination';
import { dateRangeFilter, startOfMonth, toDateOnly } from '../utils/date';
import { money, round2, ZERO } from '../utils/money';
import { badRequest, notFound } from '../utils/errors';
import { AuthContext } from '../types';
import { AuditRequestContext, recordAudit } from './audit.service';

const SORTABLE = ['date', 'createdAt', 'amount'] as const;
export interface IncomeListQuery { page?: number; limit?: number; search?: string; projectId?: string; category?: IncomeCategory; from?: string; to?: string; sortBy?: string; sortOrder?: string; }
export interface IncomeInput { amount: Prisma.Decimal.Value; date: string; category: IncomeCategory; projectId?: string; client?: string; source?: string; paymentMethod?: PaymentMethod; notes?: string; addedBy?: string; }

export function listIncomes(organizationId: string, query: IncomeListQuery) {
  const sort = resolveSort(query.sortBy, query.sortOrder, SORTABLE, 'date');
  return paginate(prisma.income, { where: andWhere({ organizationId, deletedAt: null }, query.projectId ? { projectId: query.projectId } : undefined, query.category ? { category: query.category } : undefined, dateRangeFilter(query.from, query.to) ? { date: dateRangeFilter(query.from, query.to) } : undefined, searchFilter(query.search, ['client', 'source', 'notes'])), orderBy: { [sort.field]: sort.direction }, page: query.page, limit: query.limit, include: { project: { select: { id: true, projectNumber: true, name: true } }, createdBy: { select: { id: true, fullName: true } } } });
}
export function getIncome(organizationId: string, id: string) { return findScoped(prisma.income, organizationId, id, 'Income', { include: { project: { select: { id: true, projectNumber: true, name: true } }, createdBy: { select: { id: true, fullName: true } } } }); }
async function projectExists(organizationId: string, projectId?: string) { if (projectId && !await prisma.project.findFirst({ where: { id: projectId, organizationId, deletedAt: null }, select: { id: true } })) throw notFound('Project'); }
export async function createIncome(auth: AuthContext, input: IncomeInput, ctx: AuditRequestContext) { if (round2(money(input.amount)).lessThanOrEqualTo(ZERO())) throw badRequest('Income amount must be greater than zero'); await projectExists(auth.organizationId, input.projectId); return prisma.$transaction(async tx => { const income = await tx.income.create({ data: { ...input, amount: round2(money(input.amount)), date: toDateOnly(input.date), organizationId: auth.organizationId, createdById: auth.userId } }); await recordAudit(tx, ctx, { action: 'CREATE', entityType: 'Income', entityId: income.id, summary: `Income of ${String(income.amount)} created`, newData: income }); return income; }); }
export async function updateIncome(auth: AuthContext, id: string, input: Partial<IncomeInput>, ctx: AuditRequestContext) { await projectExists(auth.organizationId, input.projectId); return prisma.$transaction(async tx => { const existing = await findScoped(tx.income, auth.organizationId, id, 'Income'); const income = await tx.income.update({ where: { id }, data: { ...input, amount: input.amount === undefined ? undefined : round2(money(input.amount)), date: input.date ? toDateOnly(input.date) : undefined } }); await recordAudit(tx, ctx, { action: 'UPDATE', entityType: 'Income', entityId: id, summary: 'Income updated', oldData: existing, newData: income }); return income; }); }
export async function deleteIncome(auth: AuthContext, id: string, ctx: AuditRequestContext) { return prisma.$transaction(async tx => { const income = await findScoped(tx.income, auth.organizationId, id, 'Income'); await tx.income.update({ where: { id }, data: { deletedAt: new Date(), deletedBy: auth.userId } }); await recordAudit(tx, ctx, { action: 'SOFT_DELETE', entityType: 'Income', entityId: id, summary: 'Income archived', oldData: income }); }); }
export async function summary(organizationId: string) { const now = new Date(); const month = startOfMonth(now); const year = new Date(Date.UTC(now.getUTCFullYear(), 0, 1)); const where = { organizationId, deletedAt: null }; const [monthTotal, yearTotal, categories] = await prisma.$transaction([prisma.income.aggregate({ where: { ...where, date: { gte: month } }, _sum: { amount: true }, _count: true }), prisma.income.aggregate({ where: { ...where, date: { gte: year } }, _sum: { amount: true }, _count: true }), prisma.income.groupBy({ by: ['category'], orderBy: { category: 'asc' }, where: { ...where, date: { gte: month } }, _sum: { amount: true }, _count: true })]); return { month: { total: monthTotal._sum.amount ?? 0, count: monthTotal._count }, year: { total: yearTotal._sum.amount ?? 0, count: yearTotal._count }, categories }; }
